version: '2'
services:
  web:
    build: .
    ports:
      - "1234:1234"
    depends_on:
      - "mysql"
    restart: always
  mysql:
    image: datajoint/mysql:5.7
    volumes:
      - ./my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    volumes:
      - ./database:/var/lib/mysql
    command: --character-set-server=utf8
    restart: always
